Rename superclass in class signature
Summary:
Part of a stack to remove Byte-Buddy "raw mode" flag, a poorly tested mode of Byte-Buddy which powers Mockito mocking under the hood.

_______________________

For data classes without an explicit parent, DCG changes the parent class from `java.lang.Object` to `DataClassSuper` to enable some Redex class merging optimization.

But, Byte-Buddy (in regular mode) relies on the class signature when resolving certain types. (You can see the signature with `javap -v <classfile>`)

For most cases, `signature` is null.
For a data class with generics in either its own type or implemented interfaces, Kotlin generates a class signature like
```lang=kotlin
data class MyDataClass<T> : Callable<Any>()
```
->
```lang=java
public final class com.foo.MyDataClass<T extends java.lang.Object> extends java.lang.Object implements java.util.concurrent.Callable<java.lang.Object>
```

DCG should remap the superclass name in the signature so Byte-Buddy can correctly analyze its bytecode.

Without this fix, we see this error:
```
java.lang.IllegalStateException: Failed to resolve super class class java.lang.Object from [class java.lang.Object]
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.compile(MethodGraph.java:685)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$AbstractBase.compile(MethodGraph.java:519)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isOverridden(MockMethodAdvice.java:191)
	at com.facebook.clientsideranking.interfaces.CSRNetworkRequestParams.getAdChannelNetworkRequestParam(CSRNetworkRequestParams.kt:23)
	at com.facebook.feed.freshfeed.adschannel.FeedCSRAdChannelControllerTest.onAdChannelRequestCompleted(FeedCSRAdChannelControllerTest.java:435)
	at com.facebook.feed.freshfeed.adschannel.FeedCSRAdChannelControllerTest.testCanMakeAdChannelRequest_withV2ConditionEnabled_checksTimeDifference(FeedCSRAdChannelControllerTest.java:540)
```

Reviewed By: RuslanLa

Differential Revision: D86162518

fbshipit-source-id: 055e99376412feb7f571ce7110eb75e5ca840255